### ISSUE TITLE
Error codes dont get returned 

### ISSUE THREAD

**Issue by cosmonoid** [punktDe/oauth2-server#10]
The returned status code is always 200 even if errors occur.

Happy that you fixed the output stream in Neos System with version 2 but I always get status code 200. I fixed it with a few lines in OAuthServerController::accessTokenAction.
`        if ($response->getStatusCode() === 200) {
            [...]
        }else{
        	$this->response->setStatusCode($response->getStatusCode());
        }`

**Comment by daniellienert** [comment]
Hey @cosmonoid, thanks for reporting that issue.
