### ISSUE TITLE
Allow to use newer versions of psr7 (semver) with v0.1.x

### ISSUE THREAD

**Issue by kaystrobach** [punktDe/oauth2-server#5]
change composer.json

```
"guzzlehttp/psr7": "~1.5"
```

to 

```
"guzzlehttp/psr7": "^1.5"
```

Will test it and then create a PR for it.

**Comment by daniellienert** [comment]
Fixed with https://github.com/punktDe/oauth2-server/commit/6afb2a0eac396e1825a1d69e03a11f7972483aa6
